apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cc-ingress
  namespace: cc-frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "INGRESS_STICKY"
    nginx.ingress.kubernetes.io/session-cookie-path: "/"
spec:
  ingressClassName: nginx
  rules:
    - host: noobalance.store        # 도메인 없으면 임시도메인
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cc-nginx-svc
                port:
                  number: 80
